- name: Update all packages to their latest version
  become: true
  apt:
    update_cache: yes

- name: Install pip3
  apt:
    name:
      - python3-pip

- name: Install Docker SDK for Python
  pip:
    name: docker
